server:
  port: 8082
  servlet:
    context-path: /interface2
    register-default-servlet: true
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
